/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed/src/lib.rs:262
-- ledger_routed::ledger_routed_hello
CREATE  FUNCTION "ledger_routed_hello"() RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_hello_wrapper';
/* </end connected objects> */

