/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:173
-- poc_ledger::poc_ledger_hello
CREATE  FUNCTION "poc_ledger_hello"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_hello_wrapper';
/* </end connected objects> */

