/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:63

    CREATE TABLE poc_test_rows (
        row_id          BIGSERIAL PRIMARY KEY,
        shard_idx       INTEGER  NOT NULL,
        slot_idx        INTEGER  NOT NULL,
        request_seq     BIGINT   NOT NULL,
        committer_tx_id BIGINT   NOT NULL,
        user_tx_xid     xid8     NOT NULL,
        pool_hash       BIGINT   NOT NULL,
        method_tag      SMALLINT NOT NULL,
        event_sku_id    BIGINT   NOT NULL,
        event_location_id BIGINT NOT NULL,
        event_qty       BIGINT   NOT NULL,
        qty_fake        BIGINT   NOT NULL,
        inserted_at     TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
    );
    CREATE INDEX poc_test_rows_committer_tx_id_idx
        ON poc_test_rows (shard_idx, committer_tx_id);
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:215
-- poc_ledger::committer::poc_ledger_apply
CREATE  FUNCTION "poc_ledger_apply"(
	"sku_id" bigint, /* i64 */
	"location_id" bigint, /* i64 */
	"qty" bigint, /* i64 */
	"method" TEXT DEFAULT 'fifo' /* alloc::string::String */
) RETURNS TABLE (
	"shard_idx" INT,  /* i32 */
	"slot_idx" INT,  /* i32 */
	"request_seq" bigint,  /* i64 */
	"committer_tx_id" bigint,  /* i64 */
	"applied_unit_cost" bigint,  /* i64 */
	"applied_total_cost" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_apply_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:156
-- poc_ledger::poc_ledger_hello
CREATE  FUNCTION "poc_ledger_hello"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_hello_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:685
-- poc_ledger::queue::poc_ledger_max_slot_probe
CREATE  FUNCTION "poc_ledger_max_slot_probe"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_max_slot_probe_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:675
-- poc_ledger::queue::poc_ledger_requests_per_shard
CREATE  FUNCTION "poc_ledger_requests_per_shard"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_requests_per_shard_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:797
-- poc_ledger::queue::poc_ledger_ring_drain_one
CREATE  FUNCTION "poc_ledger_ring_drain_one"(
	"shard_idx" INT /* i32 */
) RETURNS INT /* core::option::Option<i32> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_ring_drain_one_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:769
-- poc_ledger::queue::poc_ledger_ring_push
CREATE  FUNCTION "poc_ledger_ring_push"(
	"shard_idx" INT, /* i32 */
	"slot_idx" INT, /* i32 */
	"pool_hash" bigint, /* i64 */
	"kind_tag" INT /* i32 */
) RETURNS bigint /* core::option::Option<i64> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_ring_push_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:338
-- poc_ledger::committer::poc_ledger_shard_committer_tx_seq
CREATE  FUNCTION "poc_ledger_shard_committer_tx_seq"(
	"shard_idx" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_shard_committer_tx_seq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:670
-- poc_ledger::queue::poc_ledger_shard_count
CREATE  FUNCTION "poc_ledger_shard_count"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_shard_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:821
-- poc_ledger::queue::poc_ledger_shard_depth
CREATE  FUNCTION "poc_ledger_shard_depth"(
	"shard_idx" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_shard_depth_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:805
-- poc_ledger::queue::poc_ledger_shard_head
CREATE  FUNCTION "poc_ledger_shard_head"(
	"shard_idx" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_shard_head_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:830
-- poc_ledger::queue::poc_ledger_shard_next_request_seq
CREATE  FUNCTION "poc_ledger_shard_next_request_seq"(
	"shard_idx" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_shard_next_request_seq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:841
-- poc_ledger::queue::poc_ledger_shard_next_slot_seq
CREATE  FUNCTION "poc_ledger_shard_next_slot_seq"(
	"shard_idx" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_shard_next_slot_seq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:690
-- poc_ledger::queue::poc_ledger_shard_reset
CREATE  FUNCTION "poc_ledger_shard_reset"(
	"shard_idx" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_shard_reset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:813
-- poc_ledger::queue::poc_ledger_shard_tail
CREATE  FUNCTION "poc_ledger_shard_tail"(
	"shard_idx" INT /* i32 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_shard_tail_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:700
-- poc_ledger::queue::poc_ledger_slot_acquire
CREATE  FUNCTION "poc_ledger_slot_acquire"(
	"shard_idx" INT /* i32 */
) RETURNS INT /* core::option::Option<i32> */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_slot_acquire_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:739
-- poc_ledger::queue::poc_ledger_slot_mark_abandoned
CREATE  FUNCTION "poc_ledger_slot_mark_abandoned"(
	"shard_idx" INT, /* i32 */
	"slot_idx" INT /* i32 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_slot_mark_abandoned_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:724
-- poc_ledger::queue::poc_ledger_slot_mark_filled
CREATE  FUNCTION "poc_ledger_slot_mark_filled"(
	"shard_idx" INT, /* i32 */
	"slot_idx" INT /* i32 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_slot_mark_filled_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:754
-- poc_ledger::queue::poc_ledger_slot_recycle
CREATE  FUNCTION "poc_ledger_slot_recycle"(
	"shard_idx" INT, /* i32 */
	"slot_idx" INT /* i32 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_slot_recycle_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:708
-- poc_ledger::queue::poc_ledger_slot_state
CREATE  FUNCTION "poc_ledger_slot_state"(
	"shard_idx" INT, /* i32 */
	"slot_idx" INT /* i32 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_slot_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/queue.rs:680
-- poc_ledger::queue::poc_ledger_slots_per_shard
CREATE  FUNCTION "poc_ledger_slots_per_shard"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_ledger_slots_per_shard_wrapper';
/* </end connected objects> */

