/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-direct-c/src/lib.rs:44
-- ledger_direct_c::ledger_direct_c_hello
CREATE  FUNCTION "ledger_direct_c_hello"() RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_direct_c_hello_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-direct-c/src/submit.rs:65
-- ledger_direct_c::submit::ledger_submit_trx_c
CREATE  FUNCTION "ledger_submit_trx_c"(
	"trx_type" TEXT, /* & str */
	"source_id" bigint, /* i64 */
	"posted_at" TEXT, /* & str */
	"lines" jsonb /* pgrx :: JsonB */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_submit_trx_c_wrapper';
/* </end connected objects> */

