-- ledger-v3 migration 0003: cost-ledger core tables per design-v3 §2.2.
--
-- Depends on 0001 enums (pool_method, trx_type, line_type) and 0002 reference
-- tables (sku, location).
--
-- LOAD-BEARING constraints (do NOT relax):
--   pool UNIQUE (sku_id, location_id, identity_key)
--     — pool discovery dedup; specific-id pools set identity_key = unit_id.
--   pool_state PRIMARY KEY (pool_id, layer_seq)
--     — makes `ORDER BY pool_id, layer_seq` an index-ordered traversal for
--       FIFO ASC + LIFO DESC bulk snapshot reads (design-v3 §4.2 step 4 /
--       §5.4 step 7). plan_apply contract depends on it.
--   trx UNIQUE (trx_type, source_id)
--     — duplicate-submission detection. Path A: caller's tx aborts on the
--       second INSERT. Path B: ERRCODE_UNIQUE_VIOLATION triggers
--       pristine-replay exclusion of the dup submission.
--   trx_line UNIQUE (pool_id, trx_seq)
--     — per-pool monotonic sequence allocation. §13.1 option (a) MAX-scan
--       relies on the planner using this index for the backwards scan.

CREATE TABLE pool (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_id        BIGINT NOT NULL REFERENCES sku(id),
    location_id   BIGINT NOT NULL REFERENCES location(id),
    identity_key  BIGINT NOT NULL DEFAULT 0,
    method        pool_method NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (sku_id, location_id, identity_key)
);

CREATE TABLE pool_state (
    pool_id            BIGINT NOT NULL REFERENCES pool(id),
    layer_seq          BIGINT NOT NULL,
    qty                BIGINT NOT NULL,
    unit_cost          BIGINT NOT NULL,
    last_trx_line_id   BIGINT NOT NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (pool_id, layer_seq)
);

CREATE TABLE pool_lock (
    pool_id     BIGINT PRIMARY KEY REFERENCES pool(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE trx (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trx_type     trx_type NOT NULL,
    source_id    BIGINT NOT NULL,
    posted_at    TIMESTAMPTZ NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (trx_type, source_id)
);

CREATE TABLE trx_line (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trx_id              BIGINT NOT NULL REFERENCES trx(id),
    pool_id             BIGINT NOT NULL REFERENCES pool(id),
    line_type           line_type NOT NULL,
    source_id           BIGINT,
    qty                 BIGINT NOT NULL,
    unit_cost           BIGINT NOT NULL,
    trx_seq             BIGINT NOT NULL,
    source_trx_line_id  BIGINT REFERENCES trx_line(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (pool_id, trx_seq)
);
