-- ledger-v3 migration 0004: journal-side tables per design-v3 §2.3.
--
-- Depends on 0001 enums (posting_event_type, dimension_type), 0002 account,
-- 0003 trx_line.
--
-- LOAD-BEARING constraint:
--   posting_line_dimension PRIMARY KEY (posting_line_id, dimension_type)
--     — at most one dimension value per dimension_type per posting_line.
--
-- Per locked plan decision: PoC leaves posting_line_dimension EMPTY (no SPI
-- writes); tests that need dimensions populate via direct INSERT. The table
-- exists in the schema for forward-compatibility.

CREATE TABLE posting_line (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trx_line_id     BIGINT NOT NULL REFERENCES trx_line(id),
    event_type      posting_event_type NOT NULL,
    amount          BIGINT NOT NULL,
    debit_account   BIGINT NOT NULL REFERENCES account(id),
    credit_account  BIGINT NOT NULL REFERENCES account(id),
    posted_at       TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE posting_line_dimension (
    posting_line_id  BIGINT NOT NULL REFERENCES posting_line(id),
    dimension_type   dimension_type NOT NULL,
    dimension_id     BIGINT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (posting_line_id, dimension_type)
);
