-- ledger-v3 migration 0007: wac_periodic method + provisional postings (acct-s6fa).
--
-- Adds:
--   - pool_method enum value 'wac_periodic' (Oracle PAC convention; depletions
--     post at running pool average mid-period, then re-stated at period close
--     against actual final_avg = Σ(in-period receipt value) / Σ(in-period qty)).
--   - posting_lines_provisional: one row per wac_periodic depletion at the time
--     it is posted, capturing the provisional amount so the close hook can
--     recompute variance per row and post variance posting_lines.
--
-- Period_id is NOT stored on posting_lines_provisional. ledger_close_period
-- resolves coverage via posting_line.posted_at against accounting_period
-- (start_date, end_date) at close time. This matches the locked design
-- decision (s6fa, 2026-05-22): posted_at lookup, no SPI signature change,
-- no period_id parameter on submit/enqueue.

ALTER TYPE pool_method ADD VALUE 'wac_periodic';

CREATE TABLE posting_lines_provisional (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posting_line_id             BIGINT NOT NULL REFERENCES posting_line(id),
    pool_id                     BIGINT NOT NULL REFERENCES pool(id),
    -- depletion qty, positive (absolute value of the trx_line's signed qty)
    qty                         BIGINT NOT NULL,
    -- amount posted at the running pool average at mid-period depletion time
    provisional_amount          BIGINT NOT NULL,
    -- NULL until the close hook finalizes this row
    finalized_at                TIMESTAMPTZ,
    -- signed: variance = (final_avg * qty) - provisional_amount; may be 0
    variance_amount             BIGINT,
    -- variance posting_line.id; NULL when variance_amount == 0 (no posting
    -- emitted) or when row is unfinalized
    variance_posting_line_id    BIGINT REFERENCES posting_line(id),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (posting_line_id),
    CHECK (
        (finalized_at IS NULL
            AND variance_amount IS NULL
            AND variance_posting_line_id IS NULL)
        OR (finalized_at IS NOT NULL
            AND variance_amount IS NOT NULL)
    )
);

-- Close-hook fast path: walk unfinalized rows per pool.
CREATE INDEX posting_lines_provisional_pool_unfinalized
    ON posting_lines_provisional (pool_id)
    WHERE finalized_at IS NULL;
