/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:21
-- ledger_extension::ledger_extension_version
CREATE  FUNCTION "ledger_extension_version"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_extension_version_wrapper';
/* </end connected objects> */

