/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1935
-- ledger_extension::fifo_apply_batch_inline
CREATE  FUNCTION "fifo_apply_batch_inline"(
	"envelopes" jsonb /* pgrx::datum::json::JsonB */
) RETURNS TABLE (
	"envelope_idx" INT,  /* i32 */
	"status" TEXT,  /* alloc::string::String */
	"posting_line_id" bigint,  /* core::option::Option<i64> */
	"error_code" TEXT,  /* core::option::Option<alloc::string::String> */
	"error_message" TEXT  /* core::option::Option<alloc::string::String> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fifo_apply_batch_inline_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fifo.rs:337
-- ledger_extension::fifo::fifo_arena_capacity
CREATE  FUNCTION "fifo_arena_capacity"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fifo_arena_capacity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fifo.rs:344
-- ledger_extension::fifo::fifo_max_layers
CREATE  FUNCTION "fifo_max_layers"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fifo_max_layers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fifo.rs:354
-- ledger_extension::fifo::fifo_test_acquire_release
CREATE  FUNCTION "fifo_test_acquire_release"(
	"idx" bigint, /* i64 */
	"mode_excl" bool /* bool */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fifo_test_acquire_release_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fifo.rs:372
-- ledger_extension::fifo::fifo_test_acquire_two_sorted
CREATE  FUNCTION "fifo_test_acquire_two_sorted"(
	"idx_a" bigint, /* i64 */
	"idx_b" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fifo_test_acquire_two_sorted_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/fifo.rs:399
-- ledger_extension::fifo::fifo_test_cell_lock_addr
CREATE  FUNCTION "fifo_test_cell_lock_addr"(
	"idx" bigint /* i64 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'fifo_test_cell_lock_addr_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1175
-- ledger_extension::ledger_apply_balance_delta
CREATE  FUNCTION "ledger_apply_balance_delta"(
	"account_id" bigint, /* i64 */
	"period_id" INT, /* i32 */
	"currency_id" smallint, /* i16 */
	"ledger_kind" smallint, /* i16 */
	"amount_delta" bigint, /* i64 */
	"qty_delta" bigint /* i64 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_apply_balance_delta_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1214
-- ledger_extension::ledger_apply_batch
CREATE  FUNCTION "ledger_apply_batch"(
	"envelopes" jsonb /* pgrx::datum::json::JsonB */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_apply_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2495
-- ledger_extension::ledger_balance_lookup
CREATE  FUNCTION "ledger_balance_lookup"(
	"account_id" bigint, /* i64 */
	"period_id" INT, /* i32 */
	"currency_id" smallint, /* i16 */
	"ledger_kind" smallint /* i16 */
) RETURNS TABLE (
	"balance" bigint,  /* core::option::Option<i64> */
	"qty" bigint,  /* core::option::Option<i64> */
	"last_seq" bigint  /* core::option::Option<i64> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_balance_lookup_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2867
-- requires:
--   ledger_balance_lookup


    CREATE TABLE account_balances_rollup (
        account_id  BIGINT NOT NULL,
        period_id   INT NOT NULL,
        currency_id SMALLINT NOT NULL,
        ledger_kind SMALLINT NOT NULL,
        balance     BIGINT NOT NULL DEFAULT 0,
        qty         BIGINT NOT NULL DEFAULT 0,
        last_seq    BIGINT NOT NULL DEFAULT 0,
        drained_at  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
        PRIMARY KEY (account_id, period_id, currency_id, ledger_kind)
    );

    CREATE FUNCTION balance(
        p_account_id BIGINT,
        p_period_id INT,
        p_currency_id SMALLINT,
        p_ledger_kind SMALLINT
    ) RETURNS TABLE(balance BIGINT, qty BIGINT, last_seq BIGINT, source TEXT) AS $body$
    DECLARE
        s_balance BIGINT;
        s_qty BIGINT;
        s_last_seq BIGINT;
    BEGIN
        SELECT lookup.balance, lookup.qty, lookup.last_seq
          INTO s_balance, s_qty, s_last_seq
          FROM ledger_balance_lookup(p_account_id, p_period_id, p_currency_id, p_ledger_kind) lookup;

        IF s_balance IS NOT NULL THEN
            balance := s_balance;
            qty := s_qty;
            last_seq := s_last_seq;
            source := 'shmem';
            RETURN NEXT;
            RETURN;
        END IF;

        SELECT r.balance, r.qty, r.last_seq
          INTO balance, qty, last_seq
          FROM account_balances_rollup r
         WHERE r.account_id = p_account_id
           AND r.period_id = p_period_id
           AND r.currency_id = p_currency_id
           AND r.ledger_kind = p_ledger_kind;

        IF FOUND THEN
            source := 'rollup';
            RETURN NEXT;
            RETURN;
        END IF;

        balance := 0;
        qty := 0;
        last_seq := 0;
        source := 'none';
        RETURN NEXT;
    END;
    $body$ LANGUAGE plpgsql STABLE;
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1575
-- ledger_extension::ledger_dispatch_fifo_batch
CREATE  FUNCTION "ledger_dispatch_fifo_batch"(
	"envelopes" jsonb /* pgrx::datum::json::JsonB */
) RETURNS TABLE (
	"envelope_idx" INT,  /* i32 */
	"row_kind" TEXT,  /* alloc::string::String */
	"kind" TEXT,  /* core::option::Option<alloc::string::String> */
	"debit_account_id" bigint,  /* core::option::Option<i64> */
	"credit_account_id" bigint,  /* core::option::Option<i64> */
	"amount" bigint,  /* core::option::Option<i64> */
	"qty" bigint,  /* core::option::Option<i64> */
	"unit_cost" bigint,  /* core::option::Option<i64> */
	"layer_sentinel" INT,  /* core::option::Option<i32> */
	"layer_id" bigint,  /* core::option::Option<i64> */
	"depl_qty" bigint,  /* core::option::Option<i64> */
	"depl_cost" bigint  /* core::option::Option<i64> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_dispatch_fifo_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1329
-- ledger_extension::ledger_dispatch_wac_batch
CREATE  FUNCTION "ledger_dispatch_wac_batch"(
	"envelopes" jsonb /* pgrx::datum::json::JsonB */
) RETURNS TABLE (
	"envelope_idx" INT,  /* i32 */
	"debit_account_id" bigint,  /* i64 */
	"credit_account_id" bigint,  /* i64 */
	"amount" bigint,  /* i64 */
	"qty" bigint  /* core::option::Option<i64> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_dispatch_wac_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1102
-- ledger_extension::ledger_drain_consecutive_fails
CREATE  FUNCTION "ledger_drain_consecutive_fails"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_drain_consecutive_fails_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1111
-- ledger_extension::ledger_drain_total_failures
CREATE  FUNCTION "ledger_drain_total_failures"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_drain_total_failures_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1066
-- ledger_extension::ledger_extension_version
CREATE  FUNCTION "ledger_extension_version"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_extension_version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1081
-- ledger_extension::ledger_shmem_apply_seq
CREATE  FUNCTION "ledger_shmem_apply_seq"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_apply_seq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1071
-- ledger_extension::ledger_shmem_capacity
CREATE  FUNCTION "ledger_shmem_capacity"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_capacity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1120
-- ledger_extension::ledger_shmem_dirty_count
CREATE  FUNCTION "ledger_shmem_dirty_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_dirty_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1138
-- ledger_extension::ledger_shmem_drained_count
CREATE  FUNCTION "ledger_shmem_drained_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_drained_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1091
-- ledger_extension::ledger_shmem_insert_failure_count
CREATE  FUNCTION "ledger_shmem_insert_failure_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_insert_failure_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1076
-- ledger_extension::ledger_shmem_occupied
CREATE  FUNCTION "ledger_shmem_occupied"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_occupied_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2583
-- ledger_extension::ledger_shmem_recon
CREATE  FUNCTION "ledger_shmem_recon"() RETURNS TABLE (
	"account_id" bigint,  /* i64 */
	"shmem_balance" bigint,  /* i64 */
	"shmem_qty" bigint,  /* i64 */
	"ledger_balance" bigint,  /* core::option::Option<i64> */
	"drift" bigint  /* core::option::Option<i64> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_recon_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2831
-- ledger_extension::ledger_shmem_reset
CREATE  FUNCTION "ledger_shmem_reset"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_reset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2738
-- ledger_extension::ledger_test_panic_after_fetch_add
CREATE  FUNCTION "ledger_test_panic_after_fetch_add"(
	"account_id" bigint, /* i64 */
	"period_id" INT, /* i32 */
	"currency_id" smallint, /* i16 */
	"ledger_kind" smallint, /* i16 */
	"amount_delta" bigint, /* i64 */
	"qty_delta" bigint /* i64 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_test_panic_after_fetch_add_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2768
-- ledger_extension::ledger_test_panic_before_fetch_add
CREATE  FUNCTION "ledger_test_panic_before_fetch_add"(
	"account_id" bigint, /* i64 */
	"period_id" INT, /* i32 */
	"currency_id" smallint, /* i16 */
	"ledger_kind" smallint /* i16 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_test_panic_before_fetch_add_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:2787
-- ledger_extension::ledger_test_panic_in_exclusive
CREATE  FUNCTION "ledger_test_panic_in_exclusive"(
	"account_id" bigint, /* i64 */
	"period_id" INT, /* i32 */
	"currency_id" smallint, /* i16 */
	"ledger_kind" smallint /* i16 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_test_panic_in_exclusive_wrapper';
/* </end connected objects> */

