/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:470
-- ledger_extension::ledger_apply_balance_delta
CREATE  FUNCTION "ledger_apply_balance_delta"(
	"account_id" bigint, /* i64 */
	"period_id" INT, /* i32 */
	"currency_id" smallint, /* i16 */
	"ledger_kind" smallint, /* i16 */
	"amount_delta" bigint, /* i64 */
	"qty_delta" bigint /* i64 */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_apply_balance_delta_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:498
-- ledger_extension::ledger_balance_lookup
CREATE  FUNCTION "ledger_balance_lookup"(
	"account_id" bigint, /* i64 */
	"period_id" INT, /* i32 */
	"currency_id" smallint, /* i16 */
	"ledger_kind" smallint /* i16 */
) RETURNS TABLE (
	"balance" bigint,  /* core::option::Option<i64> */
	"qty" bigint,  /* core::option::Option<i64> */
	"last_seq" bigint  /* core::option::Option<i64> */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_balance_lookup_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:572
-- requires:
--   ledger_balance_lookup


    CREATE TABLE account_balances_rollup (
        account_id  BIGINT NOT NULL,
        period_id   INT NOT NULL,
        currency_id SMALLINT NOT NULL,
        ledger_kind SMALLINT NOT NULL,
        balance     BIGINT NOT NULL DEFAULT 0,
        qty         BIGINT NOT NULL DEFAULT 0,
        last_seq    BIGINT NOT NULL DEFAULT 0,
        drained_at  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
        PRIMARY KEY (account_id, period_id, currency_id, ledger_kind)
    );

    CREATE FUNCTION balance(
        p_account_id BIGINT,
        p_period_id INT,
        p_currency_id SMALLINT,
        p_ledger_kind SMALLINT
    ) RETURNS TABLE(balance BIGINT, qty BIGINT, last_seq BIGINT, source TEXT) AS $body$
    DECLARE
        s_balance BIGINT;
        s_qty BIGINT;
        s_last_seq BIGINT;
    BEGIN
        SELECT lookup.balance, lookup.qty, lookup.last_seq
          INTO s_balance, s_qty, s_last_seq
          FROM ledger_balance_lookup(p_account_id, p_period_id, p_currency_id, p_ledger_kind) lookup;

        IF s_balance IS NOT NULL THEN
            balance := s_balance;
            qty := s_qty;
            last_seq := s_last_seq;
            source := 'shmem';
            RETURN NEXT;
            RETURN;
        END IF;

        SELECT r.balance, r.qty, r.last_seq
          INTO balance, qty, last_seq
          FROM account_balances_rollup r
         WHERE r.account_id = p_account_id
           AND r.period_id = p_period_id
           AND r.currency_id = p_currency_id
           AND r.ledger_kind = p_ledger_kind;

        IF FOUND THEN
            source := 'rollup';
            RETURN NEXT;
            RETURN;
        END IF;

        balance := 0;
        qty := 0;
        last_seq := 0;
        source := 'none';
        RETURN NEXT;
    END;
    $body$ LANGUAGE plpgsql STABLE;
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:408
-- ledger_extension::ledger_extension_version
CREATE  FUNCTION "ledger_extension_version"() RETURNS TEXT /* &str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_extension_version_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:423
-- ledger_extension::ledger_shmem_apply_seq
CREATE  FUNCTION "ledger_shmem_apply_seq"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_apply_seq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:413
-- ledger_extension::ledger_shmem_capacity
CREATE  FUNCTION "ledger_shmem_capacity"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_capacity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:430
-- ledger_extension::ledger_shmem_dirty_count
CREATE  FUNCTION "ledger_shmem_dirty_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_dirty_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:448
-- ledger_extension::ledger_shmem_drained_count
CREATE  FUNCTION "ledger_shmem_drained_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_drained_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:418
-- ledger_extension::ledger_shmem_occupied
CREATE  FUNCTION "ledger_shmem_occupied"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_occupied_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:538
-- ledger_extension::ledger_shmem_reset
CREATE  FUNCTION "ledger_shmem_reset"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_shmem_reset_wrapper';
/* </end connected objects> */

