/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:221
-- ledger_routed_c::enqueue::ledger_enqueue_trx_batch_c
CREATE  FUNCTION "ledger_enqueue_trx_batch_c"(
	"trxs" jsonb /* pgrx :: JsonB */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_enqueue_trx_batch_c_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:51
-- ledger_routed_c::enqueue::ledger_enqueue_trx_c
CREATE  FUNCTION "ledger_enqueue_trx_c"(
	"trx_type" TEXT, /* & str */
	"source_id" bigint, /* i64 */
	"posted_at" TEXT, /* & str */
	"lines" jsonb /* pgrx :: JsonB */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_enqueue_trx_c_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:356
-- ledger_routed_c::ledger_routed_c_affinity_owned_claims_total
CREATE  FUNCTION "ledger_routed_c_affinity_owned_claims_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_affinity_owned_claims_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:364
-- ledger_routed_c::ledger_routed_c_affinity_steals_total
CREATE  FUNCTION "ledger_routed_c_affinity_steals_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_affinity_steals_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:332
-- ledger_routed_c::ledger_routed_c_arena_bump_offset
CREATE  FUNCTION "ledger_routed_c_arena_bump_offset"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_arena_bump_offset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:338
-- ledger_routed_c::ledger_routed_c_arena_freelist_count
CREATE  FUNCTION "ledger_routed_c_arena_freelist_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_arena_freelist_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:327
-- ledger_routed_c::ledger_routed_c_arena_outstanding
CREATE  FUNCTION "ledger_routed_c_arena_outstanding"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_arena_outstanding_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:315
-- ledger_routed_c::ledger_routed_c_arena_total_allocs
CREATE  FUNCTION "ledger_routed_c_arena_total_allocs"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_arena_total_allocs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:320
-- ledger_routed_c::ledger_routed_c_arena_total_frees
CREATE  FUNCTION "ledger_routed_c_arena_total_frees"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_arena_total_frees_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:377
-- ledger_routed_c::ledger_routed_c_committer_aggregate_upserts_total
CREATE  FUNCTION "ledger_routed_c_committer_aggregate_upserts_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_aggregate_upserts_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:577
-- ledger_routed_c::ledger_routed_c_committer_apply_ns_total
CREATE  FUNCTION "ledger_routed_c_committer_apply_ns_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_apply_ns_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:435
-- ledger_routed_c::ledger_routed_c_committer_deadlock_retries_total
CREATE  FUNCTION "ledger_routed_c_committer_deadlock_retries_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_deadlock_retries_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:594
-- ledger_routed_c::ledger_routed_c_committer_decode_ns_total
CREATE  FUNCTION "ledger_routed_c_committer_decode_ns_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_decode_ns_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:604
-- ledger_routed_c::ledger_routed_c_committer_dedup_ns_total
CREATE  FUNCTION "ledger_routed_c_committer_dedup_ns_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_dedup_ns_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:393
-- ledger_routed_c::ledger_routed_c_committer_dedup_skips_total
CREATE  FUNCTION "ledger_routed_c_committer_dedup_skips_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_dedup_skips_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:350
-- ledger_routed_c::ledger_routed_c_committer_drains_total
CREATE  FUNCTION "ledger_routed_c_committer_drains_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_drains_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:401
-- ledger_routed_c::ledger_routed_c_committer_dropped_submissions_total
CREATE  FUNCTION "ledger_routed_c_committer_dropped_submissions_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_dropped_submissions_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:412
-- ledger_routed_c::ledger_routed_c_committer_duplicate_redrives_total
CREATE  FUNCTION "ledger_routed_c_committer_duplicate_redrives_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_duplicate_redrives_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:454
-- ledger_routed_c::ledger_routed_c_committer_eject_total_count
CREATE  FUNCTION "ledger_routed_c_committer_eject_total_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_eject_total_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:572
-- ledger_routed_c::ledger_routed_c_committer_hydrate_ns_total
CREATE  FUNCTION "ledger_routed_c_committer_hydrate_ns_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_hydrate_ns_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:553
-- ledger_routed_c::ledger_routed_c_committer_pipeline_count
CREATE  FUNCTION "ledger_routed_c_committer_pipeline_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_pipeline_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:548
-- ledger_routed_c::ledger_routed_c_committer_pipeline_ns_total
CREATE  FUNCTION "ledger_routed_c_committer_pipeline_ns_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_pipeline_ns_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:428
-- ledger_routed_c::ledger_routed_c_committer_poisoned_total
CREATE  FUNCTION "ledger_routed_c_committer_poisoned_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_poisoned_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:369
-- ledger_routed_c::ledger_routed_c_committer_pool_lock_acquisitions_total
CREATE  FUNCTION "ledger_routed_c_committer_pool_lock_acquisitions_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_pool_lock_acquisitions_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:567
-- ledger_routed_c::ledger_routed_c_committer_pool_lock_ns_total
CREATE  FUNCTION "ledger_routed_c_committer_pool_lock_ns_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_pool_lock_ns_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:732
-- ledger_routed_c::router::ledger_routed_c_committer_queue_state_counts
CREATE  FUNCTION "ledger_routed_c_committer_queue_state_counts"() RETURNS TABLE (
	"state" TEXT,  /* String */
	"count" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_queue_state_counts_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:445
-- ledger_routed_c::ledger_routed_c_committer_takeover_count
CREATE  FUNCTION "ledger_routed_c_committer_takeover_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_takeover_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:385
-- ledger_routed_c::ledger_routed_c_committer_trx_committed_total
CREATE  FUNCTION "ledger_routed_c_committer_trx_committed_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_trx_committed_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:420
-- ledger_routed_c::ledger_routed_c_committer_tx_failures_total
CREATE  FUNCTION "ledger_routed_c_committer_tx_failures_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_tx_failures_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:582
-- ledger_routed_c::ledger_routed_c_committer_txn_ns_total
CREATE  FUNCTION "ledger_routed_c_committer_txn_ns_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_txn_ns_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:599
-- ledger_routed_c::ledger_routed_c_committer_xact_ns_total
CREATE  FUNCTION "ledger_routed_c_committer_xact_ns_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_xact_ns_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:611
-- ledger_routed_c::ledger_routed_c_hello
CREATE  FUNCTION "ledger_routed_c_hello"() RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_hello_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:759
-- ledger_routed_c::router::ledger_routed_c_ready_commit_groups
CREATE  FUNCTION "ledger_routed_c_ready_commit_groups"() RETURNS TABLE (
	"commit_group_id" bigint,  /* i64 */
	"submission_count" bigint,  /* i64 */
	"pool_keys" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_ready_commit_groups_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:461
-- ledger_routed_c::ledger_routed_c_recovery_complete
CREATE  FUNCTION "ledger_routed_c_recovery_complete"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_recovery_complete_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:481
-- ledger_routed_c::ledger_routed_c_router_commit_group_count
CREATE  FUNCTION "ledger_routed_c_router_commit_group_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_router_commit_group_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:511
-- ledger_routed_c::ledger_routed_c_router_cross_commit_group_for_update_waits
CREATE  FUNCTION "ledger_routed_c_router_cross_commit_group_for_update_waits"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_router_cross_commit_group_for_update_waits_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:494
-- ledger_routed_c::ledger_routed_c_router_entries_scanned_total
CREATE  FUNCTION "ledger_routed_c_router_entries_scanned_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_router_entries_scanned_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:523
-- ledger_routed_c::ledger_routed_c_router_max_group_size
CREATE  FUNCTION "ledger_routed_c_router_max_group_size"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_router_max_group_size_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:534
-- ledger_routed_c::ledger_routed_c_router_submission_histogram
CREATE  FUNCTION "ledger_routed_c_router_submission_histogram"() RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_router_submission_histogram_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:476
-- ledger_routed_c::ledger_routed_c_router_ticks_total
CREATE  FUNCTION "ledger_routed_c_router_ticks_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_router_ticks_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:486
-- ledger_routed_c::ledger_routed_c_router_total_submissions
CREATE  FUNCTION "ledger_routed_c_router_total_submissions"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_router_total_submissions_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:501
-- ledger_routed_c::ledger_routed_c_router_window_defers_total
CREATE  FUNCTION "ledger_routed_c_router_window_defers_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_router_window_defers_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:442
-- ledger_routed_c::enqueue::ledger_routed_c_staging_request_seq_max
CREATE  FUNCTION "ledger_routed_c_staging_request_seq_max"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_staging_request_seq_max_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:418
-- ledger_routed_c::enqueue::ledger_routed_c_staging_state_counts
CREATE  FUNCTION "ledger_routed_c_staging_state_counts"() RETURNS TABLE (
	"state" TEXT,  /* String */
	"count" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_staging_state_counts_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1113
-- ledger_routed_c::router::ledger_routed_c_test_committer_stall_hits
CREATE  FUNCTION "ledger_routed_c_test_committer_stall_hits"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_committer_stall_hits_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1191
-- ledger_routed_c::router::ledger_routed_c_test_inject_orphan_cq
CREATE  FUNCTION "ledger_routed_c_test_inject_orphan_cq"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_inject_orphan_cq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1178
-- ledger_routed_c::router::ledger_routed_c_test_reclaim_dead_committers
CREATE  FUNCTION "ledger_routed_c_test_reclaim_dead_committers"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_reclaim_dead_committers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1093
-- ledger_routed_c::router::ledger_routed_c_test_router_pid
CREATE  FUNCTION "ledger_routed_c_test_router_pid"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_router_pid_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1168
-- ledger_routed_c::router::ledger_routed_c_test_run_router_recovery_sweep
CREATE  FUNCTION "ledger_routed_c_test_run_router_recovery_sweep"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_run_router_recovery_sweep_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1070
-- ledger_routed_c::router::ledger_routed_c_test_set_bgworker_paused
CREATE  FUNCTION "ledger_routed_c_test_set_bgworker_paused"(
	"paused" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_bgworker_paused_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1082
-- ledger_routed_c::router::ledger_routed_c_test_set_committer_paused
CREATE  FUNCTION "ledger_routed_c_test_set_committer_paused"(
	"paused" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_committer_paused_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1102
-- ledger_routed_c::router::ledger_routed_c_test_set_committer_stall_us
CREATE  FUNCTION "ledger_routed_c_test_set_committer_stall_us"(
	"us" INT /* i32 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_committer_stall_us_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:639
-- ledger_routed_c::enqueue::ledger_routed_c_test_set_deadline_expired
CREATE  FUNCTION "ledger_routed_c_test_set_deadline_expired"(
	"on" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_deadline_expired_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:649
-- ledger_routed_c::enqueue::ledger_routed_c_test_set_force_arena_full
CREATE  FUNCTION "ledger_routed_c_test_set_force_arena_full"(
	"on" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_force_arena_full_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:615
-- ledger_routed_c::enqueue::ledger_routed_c_test_set_force_queue_full
CREATE  FUNCTION "ledger_routed_c_test_set_force_queue_full"(
	"on" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_force_queue_full_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1121
-- ledger_routed_c::router::ledger_routed_c_test_set_inject_deadlock_count
CREATE  FUNCTION "ledger_routed_c_test_set_inject_deadlock_count"(
	"n" INT /* i32 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_inject_deadlock_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1133
-- ledger_routed_c::router::ledger_routed_c_test_set_inject_fatal
CREATE  FUNCTION "ledger_routed_c_test_set_inject_fatal"(
	"on" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_inject_fatal_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1156
-- ledger_routed_c::router::ledger_routed_c_test_set_inject_unique
CREATE  FUNCTION "ledger_routed_c_test_set_inject_unique"(
	"on" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_inject_unique_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:1144
-- ledger_routed_c::router::ledger_routed_c_test_set_inject_xact_probe_fail
CREATE  FUNCTION "ledger_routed_c_test_set_inject_xact_probe_fail"(
	"on" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_inject_xact_probe_fail_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:627
-- ledger_routed_c::enqueue::ledger_routed_c_test_set_queue_full_after
CREATE  FUNCTION "ledger_routed_c_test_set_queue_full_after"(
	"k" INT /* i32 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_test_set_queue_full_after_wrapper';
/* </end connected objects> */

