/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:51
-- ledger_routed_c::enqueue::ledger_enqueue_trx_c
CREATE  FUNCTION "ledger_enqueue_trx_c"(
	"trx_type" TEXT, /* & str */
	"source_id" bigint, /* i64 */
	"posted_at" TEXT, /* & str */
	"lines" jsonb /* pgrx :: JsonB */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_enqueue_trx_c_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:283
-- ledger_routed_c::ledger_routed_c_arena_bump_offset
CREATE  FUNCTION "ledger_routed_c_arena_bump_offset"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_arena_bump_offset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:289
-- ledger_routed_c::ledger_routed_c_arena_freelist_count
CREATE  FUNCTION "ledger_routed_c_arena_freelist_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_arena_freelist_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:278
-- ledger_routed_c::ledger_routed_c_arena_outstanding
CREATE  FUNCTION "ledger_routed_c_arena_outstanding"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_arena_outstanding_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:266
-- ledger_routed_c::ledger_routed_c_arena_total_allocs
CREATE  FUNCTION "ledger_routed_c_arena_total_allocs"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_arena_total_allocs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:271
-- ledger_routed_c::ledger_routed_c_arena_total_frees
CREATE  FUNCTION "ledger_routed_c_arena_total_frees"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_arena_total_frees_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:314
-- ledger_routed_c::ledger_routed_c_committer_aggregate_upserts_total
CREATE  FUNCTION "ledger_routed_c_committer_aggregate_upserts_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_aggregate_upserts_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:372
-- ledger_routed_c::ledger_routed_c_committer_deadlock_retries_total
CREATE  FUNCTION "ledger_routed_c_committer_deadlock_retries_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_deadlock_retries_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:330
-- ledger_routed_c::ledger_routed_c_committer_dedup_skips_total
CREATE  FUNCTION "ledger_routed_c_committer_dedup_skips_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_dedup_skips_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:301
-- ledger_routed_c::ledger_routed_c_committer_drains_total
CREATE  FUNCTION "ledger_routed_c_committer_drains_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_drains_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:338
-- ledger_routed_c::ledger_routed_c_committer_dropped_submissions_total
CREATE  FUNCTION "ledger_routed_c_committer_dropped_submissions_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_dropped_submissions_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:349
-- ledger_routed_c::ledger_routed_c_committer_duplicate_redrives_total
CREATE  FUNCTION "ledger_routed_c_committer_duplicate_redrives_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_duplicate_redrives_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:365
-- ledger_routed_c::ledger_routed_c_committer_poisoned_total
CREATE  FUNCTION "ledger_routed_c_committer_poisoned_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_poisoned_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:306
-- ledger_routed_c::ledger_routed_c_committer_pool_lock_acquisitions_total
CREATE  FUNCTION "ledger_routed_c_committer_pool_lock_acquisitions_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_pool_lock_acquisitions_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:653
-- ledger_routed_c::router::ledger_routed_c_committer_queue_state_counts
CREATE  FUNCTION "ledger_routed_c_committer_queue_state_counts"() RETURNS TABLE (
	"state" TEXT,  /* String */
	"count" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_queue_state_counts_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:382
-- ledger_routed_c::ledger_routed_c_committer_takeover_count
CREATE  FUNCTION "ledger_routed_c_committer_takeover_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_takeover_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:322
-- ledger_routed_c::ledger_routed_c_committer_trx_committed_total
CREATE  FUNCTION "ledger_routed_c_committer_trx_committed_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_trx_committed_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:357
-- ledger_routed_c::ledger_routed_c_committer_tx_failures_total
CREATE  FUNCTION "ledger_routed_c_committer_tx_failures_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_committer_tx_failures_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:397
-- ledger_routed_c::ledger_routed_c_hello
CREATE  FUNCTION "ledger_routed_c_hello"() RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_hello_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/router.rs:680
-- ledger_routed_c::router::ledger_routed_c_ready_commit_groups
CREATE  FUNCTION "ledger_routed_c_ready_commit_groups"() RETURNS TABLE (
	"commit_group_id" bigint,  /* i64 */
	"submission_count" bigint,  /* i64 */
	"pool_keys" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_ready_commit_groups_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/lib.rs:389
-- ledger_routed_c::ledger_routed_c_recovery_complete
CREATE  FUNCTION "ledger_routed_c_recovery_complete"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_recovery_complete_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:220
-- ledger_routed_c::enqueue::ledger_routed_c_staging_request_seq_max
CREATE  FUNCTION "ledger_routed_c_staging_request_seq_max"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_staging_request_seq_max_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-routed-c/src/enqueue.rs:196
-- ledger_routed_c::enqueue::ledger_routed_c_staging_state_counts
CREATE  FUNCTION "ledger_routed_c_staging_state_counts"() RETURNS TABLE (
	"state" TEXT,  /* String */
	"count" bigint  /* i64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_routed_c_staging_state_counts_wrapper';
/* </end connected objects> */

