/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- ledger-direct/src/lib.rs:40
-- ledger_direct::ledger_direct_hello
CREATE  FUNCTION "ledger_direct_hello"() RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'ledger_direct_hello_wrapper';
/* </end connected objects> */

