/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:192
-- poc_v21_ledger::stats::poc_v21_apply_seq
CREATE  FUNCTION "poc_v21_apply_seq"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_apply_seq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1073
-- poc_v21_ledger::poc_v21_arena_bump_offset
CREATE  FUNCTION "poc_v21_arena_bump_offset"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_arena_bump_offset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1079
-- poc_v21_ledger::poc_v21_arena_freelist_count
CREATE  FUNCTION "poc_v21_arena_freelist_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_arena_freelist_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1066
-- poc_v21_ledger::poc_v21_arena_outstanding
CREATE  FUNCTION "poc_v21_arena_outstanding"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_arena_outstanding_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:522
-- poc_v21_ledger::enqueue::poc_v21_arena_stats
CREATE  FUNCTION "poc_v21_arena_stats"() RETURNS json /* Json */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_arena_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1052
-- poc_v21_ledger::poc_v21_arena_total_allocs
CREATE  FUNCTION "poc_v21_arena_total_allocs"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_arena_total_allocs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1058
-- poc_v21_ledger::poc_v21_arena_total_frees
CREATE  FUNCTION "poc_v21_arena_total_frees"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_arena_total_frees_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:2011
-- poc_v21_ledger::router::poc_v21_audit_last_run_at
CREATE  FUNCTION "poc_v21_audit_last_run_at"() RETURNS timestamp with time zone /* Option < pgrx :: datum :: TimestampWithTimeZone > */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_audit_last_run_at_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1999
-- poc_v21_ledger::router::poc_v21_audit_lost_envelopes_count
CREATE  FUNCTION "poc_v21_audit_lost_envelopes_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_audit_lost_envelopes_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1991
-- poc_v21_ledger::router::poc_v21_audit_orphans_recovered_count
CREATE  FUNCTION "poc_v21_audit_orphans_recovered_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_audit_orphans_recovered_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1986
-- poc_v21_ledger::router::poc_v21_audit_reclaims_count
CREATE  FUNCTION "poc_v21_audit_reclaims_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_audit_reclaims_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:275
-- poc_v21_ledger::stats::poc_v21_avg_batch_size
CREATE  FUNCTION "poc_v21_avg_batch_size"() RETURNS double precision /* f64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_avg_batch_size_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:231
-- poc_v21_ledger::stats::poc_v21_backpressure_count
CREATE  FUNCTION "poc_v21_backpressure_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_backpressure_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:741
-- poc_v21_ledger::poc_v21_backpressure_wake_count
CREATE  FUNCTION "poc_v21_backpressure_wake_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_backpressure_wake_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:300
-- poc_v21_ledger::stats::poc_v21_committer_pipeline_count
CREATE  FUNCTION "poc_v21_committer_pipeline_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_committer_pipeline_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:291
-- poc_v21_ledger::stats::poc_v21_committer_pipeline_ns_total
CREATE  FUNCTION "poc_v21_committer_pipeline_ns_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_committer_pipeline_ns_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:337
-- poc_v21_ledger::stats::poc_v21_committer_stage_timings
CREATE  FUNCTION "poc_v21_committer_stage_timings"() RETURNS TABLE (
	"stage" TEXT,  /* String */
	"total_ns" bigint,  /* i64 */
	"count" bigint,  /* i64 */
	"avg_ns" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_committer_stage_timings_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:375
-- poc_v21_ledger::stats::poc_v21_committer_stage_timings_reset
CREATE  FUNCTION "poc_v21_committer_stage_timings_reset"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_committer_stage_timings_reset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:77
-- poc_v21_ledger::stats::poc_v21_committer_stats
CREATE  FUNCTION "poc_v21_committer_stats"() RETURNS TABLE (
	"stat_name" TEXT,  /* String */
	"stat_value" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_committer_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:238
-- poc_v21_ledger::stats::poc_v21_committer_tx_failures
CREATE  FUNCTION "poc_v21_committer_tx_failures"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_committer_tx_failures_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:201
-- poc_v21_ledger::stats::poc_v21_committer_tx_seq
CREATE  FUNCTION "poc_v21_committer_tx_seq"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_committer_tx_seq_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:265
-- poc_v21_ledger::stats::poc_v21_eject_count
CREATE  FUNCTION "poc_v21_eject_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_eject_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:33
-- poc_v21_ledger::enqueue::poc_v21_enqueue
CREATE  FUNCTION "poc_v21_enqueue"(
	"correlation_id" uuid, /* Uuid */
	"event_type" TEXT, /* & str */
	"payload" jsonb, /* JsonB */
	"pool_keys" jsonb, /* JsonB */
	"durable_queue" bool DEFAULT false /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_enqueue_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:323
-- poc_v21_ledger::enqueue::poc_v21_enqueue_batch
CREATE  FUNCTION "poc_v21_enqueue_batch"(
	"envelopes" jsonb, /* JsonB */
	"durable_queue" bool DEFAULT false /* bool */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_enqueue_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1101
-- poc_v21_ledger::poc_v21_hello
CREATE  FUNCTION "poc_v21_hello"() RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_hello_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1090
-- poc_v21_ledger::poc_v21_invalidate_committer_caches
CREATE  FUNCTION "poc_v21_invalidate_committer_caches"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_invalidate_committer_caches_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:256
-- poc_v21_ledger::stats::poc_v21_lease_takeovers
CREATE  FUNCTION "poc_v21_lease_takeovers"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_lease_takeovers_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:130
-- poc_v21_ledger::stats::poc_v21_method_stats
CREATE  FUNCTION "poc_v21_method_stats"() RETURNS TABLE (
	"stat_name" TEXT,  /* String */
	"stat_value" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_method_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:246
-- poc_v21_ledger::stats::poc_v21_orphan_recoveries
CREATE  FUNCTION "poc_v21_orphan_recoveries"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_orphan_recoveries_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:309
-- poc_v21_ledger::stats::poc_v21_queue_depth
CREATE  FUNCTION "poc_v21_queue_depth"(
	"queue_name" TEXT /* & str */
) RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_queue_depth_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/recovery.rs:362
-- poc_v21_ledger::recovery::poc_v21_recovery_complete
CREATE  FUNCTION "poc_v21_recovery_complete"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_recovery_complete_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:837
-- poc_v21_ledger::router::poc_v21_router_force_pack_count
CREATE  FUNCTION "poc_v21_router_force_pack_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_force_pack_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:810
-- poc_v21_ledger::router::poc_v21_router_max_envelope_count
CREATE  FUNCTION "poc_v21_router_max_envelope_count"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_max_envelope_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:864
-- poc_v21_ledger::router::poc_v21_router_stats
CREATE  FUNCTION "poc_v21_router_stats"() RETURNS TABLE (
	"stat_name" TEXT,  /* String */
	"stat_value" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:783
-- poc_v21_ledger::router::poc_v21_router_stats_reset
CREATE  FUNCTION "poc_v21_router_stats_reset"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_stats_reset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:803
-- poc_v21_ledger::router::poc_v21_router_superbatch_count
CREATE  FUNCTION "poc_v21_router_superbatch_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_superbatch_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:828
-- poc_v21_ledger::router::poc_v21_router_ticks_total
CREATE  FUNCTION "poc_v21_router_ticks_total"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_ticks_total_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:817
-- poc_v21_ledger::router::poc_v21_router_total_envelopes
CREATE  FUNCTION "poc_v21_router_total_envelopes"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_total_envelopes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:505
-- poc_v21_ledger::enqueue::poc_v21_staging_state_counts
CREATE  FUNCTION "poc_v21_staging_state_counts"() RETURNS json /* Json */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_staging_state_counts_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/stats.rs:40
-- poc_v21_ledger::stats::poc_v21_staging_stats
CREATE  FUNCTION "poc_v21_staging_stats"() RETURNS TABLE (
	"stat_name" TEXT,  /* String */
	"stat_value" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_staging_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:2054
-- poc_v21_ledger::router::poc_v21_test_audit_counters_reset
CREATE  FUNCTION "poc_v21_test_audit_counters_reset"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_audit_counters_reset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:2097
-- poc_v21_ledger::router::poc_v21_test_backdate_queue_enqueued_at
CREATE  FUNCTION "poc_v21_test_backdate_queue_enqueued_at"(
	"queue_idx" bigint, /* i64 */
	"offset_ms" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_backdate_queue_enqueued_at_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:2067
-- poc_v21_ledger::router::poc_v21_test_backdate_staging_enqueued_at
CREATE  FUNCTION "poc_v21_test_backdate_staging_enqueued_at"(
	"staging_idx" bigint, /* i64 */
	"offset_ms" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_backdate_staging_enqueued_at_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1590
-- poc_v21_ledger::router::poc_v21_test_check_release_acquire_invariant
CREATE  FUNCTION "poc_v21_test_check_release_acquire_invariant"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_check_release_acquire_invariant_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:685
-- poc_v21_ledger::committer::poc_v21_test_claim_committer_entry
CREATE  FUNCTION "poc_v21_test_claim_committer_entry"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_claim_committer_entry_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:641
-- poc_v21_ledger::committer::poc_v21_test_committer_head_get
CREATE  FUNCTION "poc_v21_test_committer_head_get"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_committer_head_get_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:650
-- poc_v21_ledger::committer::poc_v21_test_committer_head_set
CREATE  FUNCTION "poc_v21_test_committer_head_set"(
	"value" bigint /* i64 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_committer_head_set_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:2894
-- poc_v21_ledger::committer::poc_v21_test_committer_tick
CREATE  FUNCTION "poc_v21_test_committer_tick"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_committer_tick_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:2148
-- poc_v21_ledger::router::poc_v21_test_force_reset_all_shmem
CREATE  FUNCTION "poc_v21_test_force_reset_all_shmem"() RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_force_reset_all_shmem_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1440
-- poc_v21_ledger::router::poc_v21_test_force_reset_injected_queue
CREATE  FUNCTION "poc_v21_test_force_reset_injected_queue"(
	"queue_idx" bigint /* i64 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_force_reset_injected_queue_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:613
-- poc_v21_ledger::committer::poc_v21_test_force_reset_slot
CREATE  FUNCTION "poc_v21_test_force_reset_slot"(
	"slot_idx" bigint /* i64 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_force_reset_slot_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1419
-- poc_v21_ledger::router::poc_v21_test_force_reset_staging
CREATE  FUNCTION "poc_v21_test_force_reset_staging"(
	"staging_idx" bigint /* i64 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_force_reset_staging_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:663
-- poc_v21_ledger::committer::poc_v21_test_inject_claimable_entry
CREATE  FUNCTION "poc_v21_test_inject_claimable_entry"(
	"slot_idx" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_inject_claimable_entry_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:556
-- poc_v21_ledger::committer::poc_v21_test_inject_orphan_into_empty
CREATE  FUNCTION "poc_v21_test_inject_orphan_into_empty"(
	"slot_idx" bigint, /* i64 */
	"fake_pid" INT, /* i32 */
	"lease_offset_ms" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_inject_orphan_into_empty_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1309
-- poc_v21_ledger::router::poc_v21_test_inject_orphaned_queue
CREATE  FUNCTION "poc_v21_test_inject_orphaned_queue"(
	"queue_idx" bigint, /* i64 */
	"sb_id" bigint, /* i64 */
	"fake_pid" INT, /* i32 */
	"staging_indices" bigint[] /* Vec < i64 > */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_inject_orphaned_queue_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1249
-- poc_v21_ledger::router::poc_v21_test_inject_staging_orphan
CREATE  FUNCTION "poc_v21_test_inject_staging_orphan"(
	"staging_idx" bigint, /* i64 */
	"sb_id" bigint, /* i64 */
	"correlation_id" uuid /* pgrx :: Uuid */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_inject_staging_orphan_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:2235
-- poc_v21_ledger::router::poc_v21_test_inject_staging_with_arena
CREATE  FUNCTION "poc_v21_test_inject_staging_with_arena"(
	"staging_idx" bigint, /* i64 */
	"sb_id" bigint, /* i64 */
	"correlation_id" uuid, /* pgrx :: Uuid */
	"payload_bytes" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_inject_staging_with_arena_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:633
-- poc_v21_ledger::committer::poc_v21_test_orphan_recover_tick
CREATE  FUNCTION "poc_v21_test_orphan_recover_tick"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_orphan_recover_tick_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:2116
-- poc_v21_ledger::router::poc_v21_test_promote_staging_to_routed
CREATE  FUNCTION "poc_v21_test_promote_staging_to_routed"(
	"staging_idx" bigint, /* i64 */
	"sb_id" bigint /* i64 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_promote_staging_to_routed_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1481
-- poc_v21_ledger::router::poc_v21_test_queue_state
CREATE  FUNCTION "poc_v21_test_queue_state"(
	"queue_idx" bigint /* i64 */
) RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_queue_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:479
-- poc_v21_ledger::enqueue::poc_v21_test_release_slot
CREATE  FUNCTION "poc_v21_test_release_slot"(
	"slot_index" bigint /* i64 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_release_slot_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/recovery.rs:353
-- poc_v21_ledger::recovery::poc_v21_test_reset_recovery_complete
CREATE  FUNCTION "poc_v21_test_reset_recovery_complete"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_reset_recovery_complete_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:965
-- poc_v21_ledger::router::poc_v21_test_router_drain
CREATE  FUNCTION "poc_v21_test_router_drain"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_router_drain_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1501
-- poc_v21_ledger::router::poc_v21_test_router_recover_tick
CREATE  FUNCTION "poc_v21_test_router_recover_tick"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_router_recover_tick_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:956
-- poc_v21_ledger::router::poc_v21_test_router_tick
CREATE  FUNCTION "poc_v21_test_router_tick"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_router_tick_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:2027
-- poc_v21_ledger::router::poc_v21_test_run_audit_sweep
CREATE  FUNCTION "poc_v21_test_run_audit_sweep"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_run_audit_sweep_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/recovery.rs:332
-- poc_v21_ledger::recovery::poc_v21_test_run_startup_recovery
CREATE  FUNCTION "poc_v21_test_run_startup_recovery"() RETURNS json /* pgrx :: Json */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_run_startup_recovery_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1568
-- poc_v21_ledger::router::poc_v21_test_set_bgworker_paused
CREATE  FUNCTION "poc_v21_test_set_bgworker_paused"(
	"paused" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_set_bgworker_paused_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1536
-- poc_v21_ledger::router::poc_v21_test_set_router_delay_us
CREATE  FUNCTION "poc_v21_test_set_router_delay_us"(
	"delay_us" INT /* i32 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_set_router_delay_us_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1550
-- poc_v21_ledger::router::poc_v21_test_set_router_reorder
CREATE  FUNCTION "poc_v21_test_set_router_reorder"(
	"enabled" bool /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_set_router_reorder_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:2083
-- poc_v21_ledger::router::poc_v21_test_set_staging_backend_pid
CREATE  FUNCTION "poc_v21_test_set_staging_backend_pid"(
	"staging_idx" bigint, /* i64 */
	"pid" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_set_staging_backend_pid_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:592
-- poc_v21_ledger::committer::poc_v21_test_slot_state
CREATE  FUNCTION "poc_v21_test_slot_state"(
	"slot_idx" bigint /* i64 */
) RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_slot_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1405
-- poc_v21_ledger::router::poc_v21_test_staging_eject_count
CREATE  FUNCTION "poc_v21_test_staging_eject_count"(
	"staging_idx" bigint /* i64 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_staging_eject_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:1386
-- poc_v21_ledger::router::poc_v21_test_staging_state
CREATE  FUNCTION "poc_v21_test_staging_state"(
	"staging_idx" bigint /* i64 */
) RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_staging_state_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:470
-- poc_v21_ledger::enqueue::poc_v21_test_take_pending
CREATE  FUNCTION "poc_v21_test_take_pending"() RETURNS bigint /* Option < i64 > */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_take_pending_wrapper';
/* </end connected objects> */

