/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:293
-- poc_v21_ledger::enqueue::poc_v21_arena_stats
CREATE  FUNCTION "poc_v21_arena_stats"() RETURNS json /* Json */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_arena_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:33
-- poc_v21_ledger::enqueue::poc_v21_enqueue
CREATE  FUNCTION "poc_v21_enqueue"(
	"correlation_id" uuid, /* Uuid */
	"event_type" TEXT, /* & str */
	"payload" jsonb, /* JsonB */
	"pool_keys" jsonb, /* JsonB */
	"durable_queue" bool DEFAULT false /* bool */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_enqueue_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:565
-- poc_v21_ledger::poc_v21_hello
CREATE  FUNCTION "poc_v21_hello"() RETURNS TEXT /* String */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_hello_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:564
-- poc_v21_ledger::router::poc_v21_router_force_pack_count
CREATE  FUNCTION "poc_v21_router_force_pack_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_force_pack_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:548
-- poc_v21_ledger::router::poc_v21_router_max_envelope_count
CREATE  FUNCTION "poc_v21_router_max_envelope_count"() RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_max_envelope_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:590
-- poc_v21_ledger::router::poc_v21_router_stats
CREATE  FUNCTION "poc_v21_router_stats"() RETURNS TABLE (
	"stat_name" TEXT,  /* String */
	"stat_value" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_stats_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:522
-- poc_v21_ledger::router::poc_v21_router_stats_reset
CREATE  FUNCTION "poc_v21_router_stats_reset"() RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_stats_reset_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:541
-- poc_v21_ledger::router::poc_v21_router_superbatch_count
CREATE  FUNCTION "poc_v21_router_superbatch_count"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_superbatch_count_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:555
-- poc_v21_ledger::router::poc_v21_router_total_envelopes
CREATE  FUNCTION "poc_v21_router_total_envelopes"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_router_total_envelopes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:276
-- poc_v21_ledger::enqueue::poc_v21_staging_state_counts
CREATE  FUNCTION "poc_v21_staging_state_counts"() RETURNS json /* Json */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_staging_state_counts_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/committer.rs:1155
-- poc_v21_ledger::committer::poc_v21_test_committer_tick
CREATE  FUNCTION "poc_v21_test_committer_tick"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_committer_tick_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:250
-- poc_v21_ledger::enqueue::poc_v21_test_release_slot
CREATE  FUNCTION "poc_v21_test_release_slot"(
	"slot_index" bigint /* i64 */
) RETURNS void
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_release_slot_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:656
-- poc_v21_ledger::router::poc_v21_test_router_drain
CREATE  FUNCTION "poc_v21_test_router_drain"() RETURNS bigint /* i64 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_router_drain_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/router.rs:648
-- poc_v21_ledger::router::poc_v21_test_router_tick
CREATE  FUNCTION "poc_v21_test_router_tick"() RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_router_tick_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/enqueue.rs:242
-- poc_v21_ledger::enqueue::poc_v21_test_take_pending
CREATE  FUNCTION "poc_v21_test_take_pending"() RETURNS bigint /* Option < i64 > */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'poc_v21_test_take_pending_wrapper';
/* </end connected objects> */

